export enum EventType {
  SETUP_GAME = "SETUP_GAME",
  START_PLAYING = "START_PLAYING",
  TAKE_TURN = "TAKE_TURN",
  PLAYER_JOINED = "PLAYER_JOINED",
  PLAYER_ATTACKED = "PLAYER_ATTACKED",
  BOAT_PLACED = "BOAT_PLACED",
  GAME_ENDED = "GAME_ENDED"
}
