@HackathonWebApi_HostAddress = http://localhost:8080

GET {{HackathonWebApi_HostAddress}}/api/example
Accept: application/json

###

GET {{HackathonWebApi_HostAddress}}/api/example/motd
Accept: application/json

###