---
config:
  theme: default
  gitGraph:
    showBranches: true
    showCommitLabel: true
---

%% syntax description, including formatting control:
%% https://mermaid.js.org/syntax/gitgraph.html

gitGraph
        commit
        branch hotfix
        checkout hotfix
        commit
        branch develop
        checkout develop
        commit id:"CUSTOM ID ANY TEXT" tag:"CUSTOM TAG ANY TEXT"
        branch featureB
        checkout featureB
        commit type:HIGHLIGHT id: "highlighted"
        checkout main
        checkout hotfix
        commit type:NORMAL id: "normal"
        checkout develop
        commit type:REVERSE id: "reversed"
        checkout featureB
        commit
        checkout main
        merge hotfix
        checkout featureB
        commit
        checkout develop
        branch featureA
        commit
        checkout develop
        merge hotfix
        checkout featureA
        commit
        checkout featureB
        commit
        checkout develop
        merge featureA
        branch release
        checkout release
        commit
        checkout main
        commit
        checkout release
        merge main
        checkout develop
        merge release