---
config:
  theme: default
---

%% syntax description, including formatting control:
%% https://mermaid.js.org/syntax/stateDiagram.html

stateDiagram-v2
    [*] --> Still
    Still --> [*]
    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]