# This is a basic workflow to help you get started with Actions

name: CI Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push for any branch and only if the frontend has changed
  push:
    branches: 
    - '**'
    paths:
    - 'frontend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.4.0
        
      - name: Install Dependencies 
        run: npm i
        working-directory: frontend
        
      - name: Build Frontend
        run: npm run-script build
        working-directory: frontend
        
      - name: Deploy Web App to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_SITE_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          output_location: ${GITHUB_REF##*/}
          action: 'upload'
          skip_app_build: true
          app_location: 'frontend/dist/frontend'
